name: Run tests on demand
on: [push]
jobs:
  run-the-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        run: |
          npm ci
          npm run cy:run:all
